# Generated by Django 2.0.6 on 2018-06-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingsystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspacetype',
            old_name='type',
            new_name='parking_type',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='type',
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='parking_type',
            field=models.CharField(choices=[('u', 'Undefined'), ('c', 'Car'), ('m', 'Motorbike')], default='u', max_length=1),
        ),
    ]
