# Generated by Django 2.0.6 on 2018-06-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingsystem', '0002_auto_20180621_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
