# Generated by Django 2.0.6 on 2018-06-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingsystem', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
