# Generated by Django 2.0.6 on 2018-06-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingsystem', '0006_auto_20180622_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
