# Generated by Django 2.0.6 on 2018-06-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingsystem', '0007_auto_20180622_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkinglot',
            options={'permissions': (('can_create', 'can create a parkinglot'),)},
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='parking_type',
            field=models.CharField(choices=[('u', 'Undefined'), ('c', 'Car'), ('m', 'Motorbike')], max_length=1, null=True),
        ),
    ]
