# Generated by Django 2.0.6 on 2018-06-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingsystem', '0008_auto_20180627_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkinglot',
            options={'permissions': (('can_create_parkinglot', 'can create a parkinglot'),)},
        ),
    ]
