# Generated by Django 2.0.6 on 2018-06-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingsystem', '0009_auto_20180627_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkinglot',
            options={},
        ),
    ]
