# Generated by Django 2.0.6 on 2018-06-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingsystem', '0010_auto_20180627_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='parking_type',
            field=models.CharField(choices=[('c', 'Car'), ('m', 'Motorbike')], max_length=1, null=True),
        ),
    ]
