# Generated by Django 2.0.6 on 2018-06-28 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parkingsystem', '0013_auto_20180628_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOwnedParking',
            fields=[
                ('standaloneparkingspace_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parkingsystem.StandaloneParkingSpace')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('parkingsystem.standaloneparkingspace',),
        ),
        migrations.DeleteModel(
            name='UserOwnedSPC',
        ),
    ]
