# Generated by Django 2.0.6 on 2018-06-29 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parkingsystem', '0014_auto_20180628_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='time_start',
        ),
        migrations.AddField(
            model_name='ticket',
            name='start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='valid_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
