# Generated by Django 2.0.6 on 2018-07-04 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parkingsystem', '0016_auto_20180702_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspace',
            name='taken_by',
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='taken_to',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
