# Generated by Django 2.0.6 on 2018-07-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingsystem', '0018_auto_20180704_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='car_space_taken',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
