# Generated by Django 2.0.6 on 2018-07-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingsystem', '0019_parkinglot_car_space_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_income',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
