# Generated by Django 2.0.6 on 2018-07-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingsystem', '0022_remove_ticket_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_income',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
